name: 'Publish application'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # Install .NET SDK
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.0.x

        # Run tests
        - name: Test
          run: dotnet test

        # Generate the website
        - name: Publish
          run: |
            dotnet tool update --global Meziantou.Framework.Html.Tool
            meziantou.html replace-value --file Dismo.Connect/wwwroot/index.html --xpath "//base/@href" --new-value "/Dismo.Connect/"
            cp Dismo.Connect/wwwroot/index.html Dismo.Connect/wwwroot/404.html
            dotnet publish Dismo.Connect/Dismo.Connect.csproj --configuration Release

        # Publish the website
        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/master' }} # Publish only when the push is on master
          uses: peaceiris/actions-gh-pages@v3.6.1
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: Dismo.Connect/bin/Release/net5.0/publish/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
